### ISSUE TITLE
Die Codierung in der URL in der Adresszeile ist nicht kompatibel zur älteren 2019 Version

### ISSUE THREAD

**Issue by MartinH-open** [menzelths/kurswahlMultiplatform#2]
Kein großes Problem - aber nach meiner Beobachtung ist für die Kurswahl die Codierung in der URL in der Adresszeile ist nicht kompatibel zur älteren 2019 Version. Irgendwann um die Jahreswende 2019/2020 wurde eine neue Codierung eingeführt. Alte URLs aus der Vorgängerversion zeigen danach eine andere Kursauswahl an ohne das einen Fehlermeldung oder ein anderer Hinweis erfolgt.
Ein allgemeiner Hinweis in der Hilfe oder sonst wohl wäre nett, dass alte URLs vor Datum XXX nicht mehr funktionieren.

**Comment by menzelths** [comment]
Das stimmt. Grund dafür war ein kleiner Fehler in der Kodierung der Kurswahl, der selten aber doch zumindest manchmal auftrat. Die Behebung des Problems ließ sich leider nur auf diesem Weg beheben.

Ich werde es nächstes Mal in die Hilfe oder in die Releasenotes aufnehmen, wenn sich das "Dateiformat" ändert.

Vielen Dank für den Hinweis.

**Comment by MartinH-open** [comment]
Danke für die Aufklärung! Wie gesagt, es ist ja kein großes Problem. Ich hatte nur eine alte URL von 2019 und die Wahlparameter waren mit Sicherheit damals anders interpretiert worden. 
Die aktuelle Version wurde zumindest an einer Sindelfinger Schule intensiv zur Vorbereitung der Kurswahl genutzt und hat somit schon gute Dienste geleistet. Danke.
Ich schließe damit dieses "Issue".
